version: "3.7"
services:
  database:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scraperdb
    build: postgres
  scraper:
    depends_on:
      - database
    build: scraper
  webpage:
    depends_on:
      - scraper
    build: webpage
    ports:
      - "8080:8080"